#!/usr/bin/python3

from products import ProductCatalog, CacheLocation
from packages import Product, Resolver, ResolverWorker, PackageSelector
from filter import PackageFilter, Classification
from database import BackingStoreDB
import sys

store = BackingStoreDB("productinfo.sql")

cache = CacheLocation("/work/projects/report/cache")
catalog = ProductCatalog(cacheLocation = cache)
catalog.updateBackingStore(store)

packageSelector = PackageSelector()

needToResolve = []
numInspected = 0

print("=== about to enumerate latest packages ===")
for pinfo in store.enumerateLatestPackages():
	numInspected += 1

	if pinfo.name.endswith('-32bit'):
		continue

	pkg = store.retrievePackage(pinfo)

	product = pkg.product
	if product is None:
		raise Exception(f"{pkg.fullname()} product id {pkg.productId} resolves to None")

	if pkg.arch not in ('src', 'nosrc'):
		needToResolve.append(pkg)

# alternatively, we could just drop and recreate the entire tree table
store.dependencyTreeExcise(list(_.backingStoreId for _ in needToResolve))

numFound = len(needToResolve)
print(f"Inspected {numInspected} packages, will compute dependency on {numFound} packages")

resolver = Resolver(backingStore = store)
resolver.declareConditional('kernel', True)
resolver.declareConditional('systemd', True)
resolver.declareConditional('libyui-qt', True)
resolver.declareConditional('python38-gobject', True)
resolver.declareConditional('python39-gobject', True)

worker = ResolverWorker(resolver)
alreadyResolved = set()

print("=== About to resolve dependencies ===")
counter = 0
edges = set()
for pkg in needToResolve:
	if pkg in alreadyResolved:
		continue

	alreadyResolved.add(pkg)
	queue = [pkg]
	while queue:
		pkg = queue.pop(0)

		counter += 1
		if counter % 10 == 0:
			store.addEdgeSetToTree(edges)
			edges = set()

			print(f"\r{counter} packages; lookup cache: {worker.formatCacheStats()} ...", end = "")
			sys.stdout.flush()

		for dep, target in worker.resolveDownward(pkg):
			if target not in alreadyResolved:
				# print(f"{pkg.fullname()} -> {target.name}")
				queue.append(target)
				alreadyResolved.add(target)

			edges.add((pkg.backingStoreId, target.backingStoreId, dep.backingStoreId))

print(" done.")

print("==============")

if worker.problems:
	print("The resolver flagged the following problems")
	worker.problems.show()
