#!/usr/bin/python3

from products import ProductCatalog, CacheLocation
from packages import Product, Resolver, ResolverWorker, PackageSelector, ResolverPreferences, PackageCollection
from filter import PackageFilter, Classification
from database import BackingStoreDB
import sys
from options import Application

application = Application('build-dependency-tree')
dummy = application.catalog

store = application.backingStore

# Load the default package filter and labelling
# We need this for package preferences
packageFilter = PackageFilter()

needToResolve = PackageCollection()
numInspected = 0

print("=== about to enumerate latest packages ===")
for pinfo in store.enumerateLatestPackages():
	numInspected += 1

	if pinfo.name.endswith('-32bit'):
		continue

	pkg = store.retrievePackage(pinfo)

	product = pkg.product
	if product is None:
		raise Exception(f"{pkg.fullname()} cannot determine product (product id {pkg.productId}")

	if pkg.arch not in ('src', 'nosrc'):
		needToResolve.add(pkg)

arch = needToResolve.uniqueArch

# alternatively, we could just drop and recreate the entire tree table
store.dependencyTreeExcise(list(_.backingStoreId for _ in needToResolve))

numFound = len(needToResolve)
print(f"Inspected {numInspected} packages, will compute dependency on {numFound} packages")
print(f"Architecture {arch}")

resolver = Resolver(backingStore = store)
resolver.declareConditional('kernel', True)
resolver.declareConditional('systemd', True)
resolver.declareConditional('libyui-qt', True)
resolver.declareConditional('python38-gobject', True)
resolver.declareConditional('python39-gobject', True)

worker = ResolverWorker(resolver)

context = worker.contextForArch(arch)

preferences = ResolverPreferences()
preferences.setPackagePreferences(packageFilter.packagePreferences)
alreadyResolved = set()

print("=== About to resolve dependencies ===")
counter = 0
edges = set()
for pkg in needToResolve:
	if pkg in alreadyResolved:
		continue

	alreadyResolved.add(pkg)
	queue = [pkg]
	while queue:
		pkg = queue.pop(0)

		assert(pkg.arch != 'src')

		counter += 1
		if counter % 10 == 0:
			store.addEdgeSetToTree(edges)
			edges = set()

			print(f"\r{counter} packages; lookup cache: {worker.formatCacheStats()} ...", end = "")
			sys.stdout.flush()

		for dep, target in context.resolveDownward(preferences, pkg):
			if target not in alreadyResolved:
				# print(f"{pkg.fullname()} -> {target.name}")
				queue.append(target)
				alreadyResolved.add(target)

			edges.add((pkg.backingStoreId, target.backingStoreId, dep.backingStoreId))

if edges:
	store.addEdgeSetToTree(edges)
	del edges

print(f"\r{counter} packages; lookup cache: {worker.formatCacheStats()} ... done.")
print("==============")

if worker.problems:
	print("The resolver flagged the following problems")
	worker.problems.show()
