#!/usr/bin/python3


from repos import RepoDict, UrlCacheStrategy
from products import ProductCatalog, CacheLocation
from packages import Product, Resolver, ResolverWorker, ResolverPreferences, PackageSelector, PackageCollection
from filter import PackageFilter, Classification, PotentialClassification
from options import Application
from writers import StandardWriter, TableWriter, XmlWriter

application = Application('build-dependency-tree')
dummy = application.catalog

store = application.backingStore
store.enableDependencyTreeLookups()
store.enableSourceLookups()

classificationScheme = Classification.Scheme()
packageFilter = PackageFilter(scheme = classificationScheme)
unclassified = packageFilter.makeBinaryGroup("Unclassified")

labelOrder = classificationScheme.createOrdering(Classification.TYPE_BINARY)

potentialClassification = PotentialClassification(labelOrder)

packageSelector = PackageSelector()
collection = PackageCollection()

resolver = Resolver(backingStore = store)

if True:
	store.fixupLatest()
	store.fixupBuilds()
	store.fixupRequirements()
	# stop

for pinfo in store.enumerateLatestPackages():
	pkg = store.retrievePackage(pinfo)
	assert(pkg.product == pinfo.product)

	verdict = packageFilter.apply(pkg, pinfo.product)
	if verdict is not None:
		verdict.labelPackage(pkg)
		print(f"{pkg} is placed in {verdict.label} by package filter rules")
	else:
		# we currently have no good way to properly mark unclassified packages
		# group = unclassified
		pass

	collection.add(pkg)

def flattenGroupList(type, names):
	labelSet = set()
	for name in names:
		label = classificationScheme.getLabel(name)
		if label is None:
			print(f"Warning: no label {name}")
			continue

		assert(label.type == type)

		belowSet = labelOrder.downwardClosureFor(label)
		for below in belowSet:
			if below.type != type:
				raise Exception(f"downward closure for label {label} contains {below.type} label {below}")
		labelSet.update(belowSet)

	return labelOrder.bottomUpTraversal(labelSet)

binaryGroupNames = ("@Core", "@HostCore", "@Kernel", "@UpdateStack", "@CoreLibraries+odbc", "@X11Libraries", "@MinimalSystemd", "@DesktopBuild")
binaryGroupNames = ("@CoreLibraries", "@Core0", "@CoreLibraries+python")
binaryTraversal = flattenGroupList(Classification.TYPE_BINARY, binaryGroupNames)
#sourceTraversal = flattenGroupList(Classification.TYPE_SOURCE, ("Core", "KernelPlus"))
sourceTraversal = []

worker = ResolverWorker(resolver)
problemLog = worker.problems

for labelName in ("@Gnome", "@Texlive", "@Emacs", "@Vim", "@Qt"):
	label = classificationScheme.getLabel(labelName)
	assert(label)
	print(f"Ignoring all problems for label {label}")
	problemLog.ignore(label)

productArchitecture = store.getProperty("arch")
if productArchitecture is None:
	raise Exception("database does not record architecture of original query")

resolverContext = worker.contextForArch(productArchitecture)
classificationContext = Classification.ClassificationContext(worker, productArchitecture, labelOrder, store)

def classifyAutoFlavors(label, labelledPackages):
	# Do not apply auto-flavors to groups that are already a flavor of some other group.
	# Otherwise, we end up with labels like @HostNetworking+gnome+devel+unused
	if label.flavorBase is not None:
		return

	classifier = Classification.AutoflavorPackageClosure(problemLog, store)
	classifier.classify(labelledPackages)
	for flavorDef in packageFilter.autoFlavors:
		found = classifier.getFlavor(flavorDef.name)
		if found is None:
			continue

		if label.autoFlavorCanBeMerged(flavorDef.label):
			# The autoflavor has a disposition of "merge", or
			# it has a disposition of "maybe_merge" and all its requirements
			# are already present in the base label
			relabeled = classifier.labelFlavoredPackages(flavorDef.name, label)
			packageFilter.updateGroup(label, relabeled)

			if False:
				print(f"Merged {len(relabeled)} packages into {label}")
				for l in relabeled:
					print(f"  {l}")
		elif flavorDef.label.disposition == Classification.DISPOSITION_IGNORE:
			pass
		else:
			# we're not really instantiating a new flavor here
			flavorLabel = label.getBuildFlavor(flavorDef.name)
			relabeled = classifier.labelFlavoredPackages(flavorDef.name, flavorLabel)
			packageFilter.updateGroup(flavorLabel, relabeled)

def classifyRuntimeDependenciesFlexible(labelledPackages):
	# Step 1: build the runtime dependency closure
	classifier = Classification.FlexibleDownwardClosure(classificationContext, potentialClassification)
	classifier.classify(labelledPackages)

def classifyRuntimeDependencies(label):
	global binaryTraversal

	group = packageFilter.makeBinaryGroup(label.name)
	labelledPackages = group.packages

	print(f"Classify packages belonging to {group.label}")

	# Step 0: automatically add compatible build flavors of subordinate groups
	# iff we satisfy all their dependencies
	if True:
		label.autoSelectCompatibleFlavors()
	else:
		update = set()
		for req in label.runtimeRequires:
			for flavor in req.flavors:
				if flavor.allFlavorRequirementsSatisfied(label):
					print(f"{label} auto-selected {flavor} via {req}")
					update.add(flavor)
		for flavor in update:
			# print(f" {label} -> enable {flavor}")
			label.addRuntimeDependency(flavor)

	# Step 1: build the runtime dependency closure
	classifier = Classification.DownwardClosure(classificationContext, label)
	classifier.classify(labelledPackages)
	labelledPackages = classifier.result

	packageFilter.updateGroup(label, labelledPackages)

	# for each of the newly classified packages, see if we have sibling packages that
	# we can slot into one of the autoflavors like +devel, +python etc.
	classifyAutoFlavors(label, labelledPackages)

	# Step N: sort all other sibling packages into $Group+unused.
	# To avoid infinite recursion, do not perform this step for the +unused flavor itself.
	if not label.name.endswith("unused"):
		while group.label.flavorBase:
			group = packageFilter.makeBinaryGroup(group.label.flavorBase.name)

		siblingGroup = packageFilter.makeFlavorGroup(group, "unused")
		siblingGroup.label.autoSelect = False

		classifier = Classification.SiblingPackageClosure(problemLog, siblingGroup.label, store)
		classifier.classify(labelledPackages)
		siblingGroup.update(classifier.result)

def classifyBuildDependencies(label):
	global binaryTraversal

	# get the build requirements of this label and make sure we've satisfied all their runtime
	# requirements
	for buildLabel in binaryTraversal.flattenBuildRequirements(label):
		classifyRuntimeDependencies(buildLabel)

	group = packageFilter.makeBinaryGroup(label.name)

	classifier = Classification.BuildRequiresClosure(problemLog, label, store)
	packagesNeededForBuild = classifier.classify(group.packages)

	unlabelledPackages = classifier.unlabelledPackages
	if unlabelledPackages:
		print(f"{label.name} has {len(unlabelledPackages)} unclassified build requirements")

		print(f"Classifying new build requirements for {label}")
		classifier = Classification.UnknownPackageClassifier(worker, productArchitecture, label)
		classifier.classify(unlabelledPackages)

		# FIXME: This should also be part of the problem report
		for suggestedLabel, candidatePackages in classifier.suggestions:
			print(f"   Classifier suggests label {suggestedLabel} for these package(s)")
			for cand in candidatePackages:
				print(f"      {cand.shortname}")

processedBinaryLabels = []

# Having classified packages that are referenced in the filter definition,
# inspect their sibling packages and see whether they have been identified
# by one of the auto flavors like python or ruby. If that's the case
# label them correspondingly (ie as Foo+python, Foo+ruby, etc).
for label in labelOrder.bottomUpTraversal():
	group = packageFilter.makeBinaryGroup(label.name)
	classifyAutoFlavors(label, group.packages)

classifier = Classification.FlexibleDownwardClosure(classificationContext, potentialClassification)
#for label in labelOrder.bottomUpTraversal():
#	group = packageFilter.makeBinaryGroup(label.name)
#	classifier.classify(group.closure)
classifier.classify(collection)

verdict = potentialClassification.solve()

# not very efficient
for pkg, label, labelReason in verdict:
	packageFilter.labelOnePackage(pkg, label, labelReason)

for label in binaryTraversal:
	# classifyBuildDependencies(label)
	pass

if False:
	for label in sourceTraversal:
		group = packageFilter.makeSourceGroup(label.name)

		print(f"Classify packages belonging to source project {group.label}")

		classifier = Classification.BuildRequireClosure(worker, productArchitecture, label)
		assert(classifier)
		for component in label.buildRequires:
			componentGroup = packageFilter.makeBinaryGroup(component.name)
			assert(componentGroup)
			classifier.classify(componentGroup.packages)

		closure[label.name] = classifier.result

	closure[label.name] = classifier.result

writer = TableWriter("packages.csv")
writer.write(packageFilter, labelOrder)

writer = XmlWriter("packages.xml")
writer.write(packageFilter, labelOrder)

if False and problemLog:
	writer.writeProblems(problemLog)
