#!/usr/bin/python3
#
# To download the OBS data for Dolomite, invoke like this:
#  ./obs-download-data --family dolomite --db dolomite.db
#

forceRefresh = True

from options import Application
from obsclnt import OBSClient, OBSProject

application = Application('obs-download-data')

store = application.backingStore

# Make sure we have all the products that we use recorded in the database
application.catalog.updateBackingStore(store)

# store the arch we're asked to look at, so that we don't
# have to play guessing games later on
store.putProperty("arch", application.architecture)

obsInstanceHostname = "api.suse.de"

obs = application.obsClient

for release in application.enumerateProducts():

	product = release.createEmptyProduct()

	infomsg(f"Downloading OBS information for release {release}")

	projects = []
	for bp in release.buildProjects:
		infomsg(f"  {bp}")

		project = OBSProject(bp, product)

		cachePath = application.getCachePath(f"obs/{obs.hostname}")
		project.setCachePath(cachePath)

		project.primeCache(obs)
		projects.append(project)

	# now we should have everything we need. only go to OBS if something's really missing
	obs.setCacheStrategy('opportunistic')

	for project in projects:
		project.updateBinaryList(obs)
		project.updateBackingStore(application.backingStore, obs)
