#!/usr/bin/python3

forceRefresh = True

import argparse
from repos import RepoDict, UrlCacheStrategy
from products import ProductCatalog, CacheLocation
from packages import Product, Resolver, ResolverWorker
from filter import PackageFilter, Classification
from database import BackingStoreDB
from obsclnt import OBSClient, OBSProject

from options import Application

application = Application('repo-download')

class CountDict:
	def __init__(self):
		self._d = dict()

	def add(self, name):
		try:
			self._d[name] += 1
		except:
			self._d[name] = 1

	def __getitem__(self, name):
		return self._d[name]

	@property
	def names(self):
		return sorted(self._d.keys())

class PackageInfo:
	def __init__(self, name):
		self.name = name
		self.groups = set()
		self.sawEmptyGroup = False

	def foundGroup(self, groupName):
		if not groupName:
			self.sawEmptyGroup = True
		else:
			self.groups.add(groupName)

class ProductStats:
	def __init__(self):
		self.packages = {}

	def found(self, src, classifiedAs):
		try:
			pi = self.packages[src.name]
		except:
			pi = PackageInfo(src.name)
			self.packages[src.name] = pi

		pi.foundGroup(classifiedAs)

class PackageMap(dict):
	def add(self, pkg, product):
		self[pkg.name] = (pkg, product)

	def enumerate(self):
		return iter(self.values())


groupUpdateCount = CountDict()
productInfo = ProductStats()

packageMap = PackageMap()

obsInstanceHostname = "api.suse.de"

obs = OBSClient(f"https://{obsInstanceHostname}")
obs.setCachePath("cache/http")

if True:
	for release in application.enumerateProducts():

		product = release.createEmptyProduct()

		print(f"Release {release}")
		for bp in release.buildProjects:
			print(f"  {bp}")

			project = OBSProject(bp, product)
			project.setCachePath(f"cache/obs/{obsInstanceHostname}")
			project.updateBinaryList(obs)
			project.updateBackingStore(application.backingStore, obs)
			continue

for release in application.enumerateProducts():
	print(f"Found {release}")

	# FIXME: product = release.createEmptyProduct() instead
	product = Product()
	product.productId = release.backingStoreId

	# First pass: load relevant info from all repos
	for repo in release.getRepositories():
		repo.load(product, refresh = repo.REFRESH_MAYBE)

	# Second pass: resolve package sources
	for repo in release.getRepositories():
		repo.resolveSourcePackages(product)

	product.updateBackingStore(application.backingStore)

	for pkg in product.packages.values():
		packageMap.add(pkg, release)

exit(0)

# CRUFT THAT WILL GO ELSEWHERE BELOW

classificationScheme = Classification.Scheme()
packageFilter = PackageFilter(scheme = classificationScheme)
unclassified = packageFilter.makeGroup("Unclassified")

resolver = Resolver()
for pkg, product in packageMap.enumerate():
	resolver.addPackage(pkg)

	verdict = packageFilter.apply(pkg, product)
	if verdict is not None:
		verdict.labelPackage(pkg)
		group = verdict.group
	else:
		group = unclassified

	productInfo.found(pkg, group.name)

	groupUpdateCount.add(group.name)

def resolveGroup(groupName, worker, alreadyResolved):
	group = packageFilter.makeGroup(groupName)

	alreadyResolved.add(group.label)
	for usedLabel in group.label.uses:
		if usedLabel not in alreadyResolved:
			resolveGroup(usedLabel.name, worker, alreadyResolved)

	print(f"Classify {groupName} with label {group.label}")
	classifier = Classification.DownwardClosure(worker, group.label)
	classifier.classify(group.packages)

worker = ResolverWorker(resolver)
alreadyResolved = set()
for groupName in ("@Core", "@Kernel", "@UpdateStack"):
	resolveGroup(groupName, worker, alreadyResolved)

if worker.problems:
	print("The resolver flagged the following problems")
	worker.problems.show()
